//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from BtnStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class BtnStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.BtnStrings", typeof(BtnStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Exit => ResourceManager.GetString(nameof(Exit), _resourceCulture);

        public static string FixVersion => ResourceManager.GetString(nameof(FixVersion), _resourceCulture);

        public static string HistoryRollback => ResourceManager.GetString(nameof(HistoryRollback), _resourceCulture);

        public static string ManualUpdate => ResourceManager.GetString(nameof(ManualUpdate), _resourceCulture);

        public static string OpenNewSettings => ResourceManager.GetString(nameof(OpenNewSettings), _resourceCulture);

        public static string OpenPluginManager => ResourceManager.GetString(nameof(OpenPluginManager), _resourceCulture);

        public static string Reset => ResourceManager.GetString(nameof(Reset), _resourceCulture);

        public static string Restart => ResourceManager.GetString(nameof(Restart), _resourceCulture);

        public static string Rollback => ResourceManager.GetString(nameof(Rollback), _resourceCulture);

        public static string VersionFix => ResourceManager.GetString(nameof(VersionFix), _resourceCulture);
    }
}