//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from CommonStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class CommonStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.CommonStrings", typeof(CommonStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AskEachTime => ResourceManager.GetString(nameof(AskEachTime), _resourceCulture);

        public static string CollapseNavSidebar => ResourceManager.GetString(nameof(CollapseNavSidebar), _resourceCulture);

        public static string Color => ResourceManager.GetString(nameof(Color), _resourceCulture);

        public static string Color_Black => ResourceManager.GetString(nameof(Color_Black), _resourceCulture);

        public static string Color_Blue => ResourceManager.GetString(nameof(Color_Blue), _resourceCulture);

        public static string Color_Default => ResourceManager.GetString(nameof(Color_Default), _resourceCulture);

        public static string Color_Green => ResourceManager.GetString(nameof(Color_Green), _resourceCulture);

        public static string Color_Orange => ResourceManager.GetString(nameof(Color_Orange), _resourceCulture);

        public static string Color_Purple => ResourceManager.GetString(nameof(Color_Purple), _resourceCulture);

        public static string Color_Red => ResourceManager.GetString(nameof(Color_Red), _resourceCulture);

        public static string Color_White => ResourceManager.GetString(nameof(Color_White), _resourceCulture);

        public static string Color_Yellow => ResourceManager.GetString(nameof(Color_Yellow), _resourceCulture);

        public static string Common_Close => ResourceManager.GetString(nameof(Common_Close), _resourceCulture);

        public static string Common_Off => ResourceManager.GetString(nameof(Common_Off), _resourceCulture);

        public static string Common_On => ResourceManager.GetString(nameof(Common_On), _resourceCulture);

        public static string EraserSize_SwitchHint => ResourceManager.GetString(nameof(EraserSize_SwitchHint), _resourceCulture);

        public static string Hotkey_NotSet => ResourceManager.GetString(nameof(Hotkey_NotSet), _resourceCulture);

        public static string Mode_Normal => ResourceManager.GetString(nameof(Mode_Normal), _resourceCulture);

        public static string Mode_PPTOnly => ResourceManager.GetString(nameof(Mode_PPTOnly), _resourceCulture);

        public static string No => ResourceManager.GetString(nameof(No), _resourceCulture);

        public static string ShowNavSidebar => ResourceManager.GetString(nameof(ShowNavSidebar), _resourceCulture);

        public static string Size_Large => ResourceManager.GetString(nameof(Size_Large), _resourceCulture);

        public static string Size_Medium => ResourceManager.GetString(nameof(Size_Medium), _resourceCulture);

        public static string Size_Small => ResourceManager.GetString(nameof(Size_Small), _resourceCulture);

        public static string Size_VeryLarge => ResourceManager.GetString(nameof(Size_VeryLarge), _resourceCulture);

        public static string Size_VerySmall => ResourceManager.GetString(nameof(Size_VerySmall), _resourceCulture);

        public static string Time_End => ResourceManager.GetString(nameof(Time_End), _resourceCulture);

        public static string Time_Start => ResourceManager.GetString(nameof(Time_Start), _resourceCulture);

        public static string Yes => ResourceManager.GetString(nameof(Yes), _resourceCulture);
    }
}