//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from ConfigStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class ConfigStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.ConfigStrings", typeof(ConfigStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Delete => ResourceManager.GetString(nameof(Delete), _resourceCulture);

        public static string Desc => ResourceManager.GetString(nameof(Desc), _resourceCulture);

        public static string Label => ResourceManager.GetString(nameof(Label), _resourceCulture);

        public static string SaveAs => ResourceManager.GetString(nameof(SaveAs), _resourceCulture);

        public static string Title => ResourceManager.GetString(nameof(Title), _resourceCulture);
    }
}