//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from FloatingBarStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class FloatingBarStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.FloatingBarStrings", typeof(FloatingBarStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Board_AutoHide => ResourceManager.GetString(nameof(Board_AutoHide), _resourceCulture);

        public static string Board_Background => ResourceManager.GetString(nameof(Board_Background), _resourceCulture);

        public static string Board_ClearInk => ResourceManager.GetString(nameof(Board_ClearInk), _resourceCulture);

        public static string Board_ClearInkAndHistory => ResourceManager.GetString(nameof(Board_ClearInkAndHistory), _resourceCulture);

        public static string Board_DeleteThisPage => ResourceManager.GetString(nameof(Board_DeleteThisPage), _resourceCulture);

        public static string Board_Eraser => ResourceManager.GetString(nameof(Board_Eraser), _resourceCulture);

        public static string Board_EraserOptions => ResourceManager.GetString(nameof(Board_EraserOptions), _resourceCulture);

        public static string Board_EraserShape => ResourceManager.GetString(nameof(Board_EraserShape), _resourceCulture);

        public static string Board_EraserShape_Blackboard => ResourceManager.GetString(nameof(Board_EraserShape_Blackboard), _resourceCulture);

        public static string Board_EraserShape_Circle => ResourceManager.GetString(nameof(Board_EraserShape_Circle), _resourceCulture);

        public static string Board_Exit => ResourceManager.GetString(nameof(Board_Exit), _resourceCulture);

        public static string Board_Gesture => ResourceManager.GetString(nameof(Board_Gesture), _resourceCulture);

        public static string Board_GestureOptions => ResourceManager.GetString(nameof(Board_GestureOptions), _resourceCulture);

        public static string Board_Highlighter => ResourceManager.GetString(nameof(Board_Highlighter), _resourceCulture);

        public static string Board_InsertImage => ResourceManager.GetString(nameof(Board_InsertImage), _resourceCulture);

        public static string Board_LaserPen => ResourceManager.GetString(nameof(Board_LaserPen), _resourceCulture);

        public static string Board_MultiTouchWriting => ResourceManager.GetString(nameof(Board_MultiTouchWriting), _resourceCulture);

        public static string Board_NewPage => ResourceManager.GetString(nameof(Board_NewPage), _resourceCulture);

        public static string Board_NextPage => ResourceManager.GetString(nameof(Board_NextPage), _resourceCulture);

        public static string Board_Page => ResourceManager.GetString(nameof(Board_Page), _resourceCulture);

        public static string Board_Pen => ResourceManager.GetString(nameof(Board_Pen), _resourceCulture);

        public static string Board_PreviousPage => ResourceManager.GetString(nameof(Board_PreviousPage), _resourceCulture);

        public static string Board_Redo => ResourceManager.GetString(nameof(Board_Redo), _resourceCulture);

        public static string Board_Screenshot => ResourceManager.GetString(nameof(Board_Screenshot), _resourceCulture);

        public static string Board_Select => ResourceManager.GetString(nameof(Board_Select), _resourceCulture);

        public static string Board_SelectImage => ResourceManager.GetString(nameof(Board_SelectImage), _resourceCulture);

        public static string Board_Shape => ResourceManager.GetString(nameof(Board_Shape), _resourceCulture);

        public static string Board_ShapeHintLongPress => ResourceManager.GetString(nameof(Board_ShapeHintLongPress), _resourceCulture);

        public static string Board_Size => ResourceManager.GetString(nameof(Board_Size), _resourceCulture);

        public static string Board_StrokeEraser => ResourceManager.GetString(nameof(Board_StrokeEraser), _resourceCulture);

        public static string Board_Tools => ResourceManager.GetString(nameof(Board_Tools), _resourceCulture);

        public static string Board_TwoFingerMove => ResourceManager.GetString(nameof(Board_TwoFingerMove), _resourceCulture);

        public static string Board_TwoFingerRotate => ResourceManager.GetString(nameof(Board_TwoFingerRotate), _resourceCulture);

        public static string Board_TwoFingerZoom => ResourceManager.GetString(nameof(Board_TwoFingerZoom), _resourceCulture);

        public static string Board_Undo => ResourceManager.GetString(nameof(Board_Undo), _resourceCulture);

        public static string FloatingBar_Annotate => ResourceManager.GetString(nameof(FloatingBar_Annotate), _resourceCulture);

        public static string FloatingBar_AreaEraser => ResourceManager.GetString(nameof(FloatingBar_AreaEraser), _resourceCulture);

        public static string FloatingBar_Clear => ResourceManager.GetString(nameof(FloatingBar_Clear), _resourceCulture);

        public static string FloatingBar_ClearAndMouse => ResourceManager.GetString(nameof(FloatingBar_ClearAndMouse), _resourceCulture);

        public static string FloatingBar_ExitButton => ResourceManager.GetString(nameof(FloatingBar_ExitButton), _resourceCulture);

        public static string FloatingBar_Freeze => ResourceManager.GetString(nameof(FloatingBar_Freeze), _resourceCulture);

        public static string FloatingBar_Geometry => ResourceManager.GetString(nameof(FloatingBar_Geometry), _resourceCulture);

        public static string FloatingBar_Gesture_MultiTouchWriting => ResourceManager.GetString(nameof(FloatingBar_Gesture_MultiTouchWriting), _resourceCulture);

        public static string FloatingBar_Gesture_TwoFingerMove => ResourceManager.GetString(nameof(FloatingBar_Gesture_TwoFingerMove), _resourceCulture);

        public static string FloatingBar_Gesture_TwoFingerRotate => ResourceManager.GetString(nameof(FloatingBar_Gesture_TwoFingerRotate), _resourceCulture);

        public static string FloatingBar_Gesture_TwoFingerZoom => ResourceManager.GetString(nameof(FloatingBar_Gesture_TwoFingerZoom), _resourceCulture);

        public static string FloatingBar_GestureButton => ResourceManager.GetString(nameof(FloatingBar_GestureButton), _resourceCulture);

        public static string FloatingBar_GesturePanelTitle => ResourceManager.GetString(nameof(FloatingBar_GesturePanelTitle), _resourceCulture);

        public static string FloatingBar_Hide => ResourceManager.GetString(nameof(FloatingBar_Hide), _resourceCulture);

        public static string FloatingBar_LassoSelect => ResourceManager.GetString(nameof(FloatingBar_LassoSelect), _resourceCulture);

        public static string FloatingBar_Mouse => ResourceManager.GetString(nameof(FloatingBar_Mouse), _resourceCulture);

        public static string FloatingBar_StrokeEraser => ResourceManager.GetString(nameof(FloatingBar_StrokeEraser), _resourceCulture);

        public static string FloatingBar_Unfreeze => ResourceManager.GetString(nameof(FloatingBar_Unfreeze), _resourceCulture);

        public static string FloatingBar_Whiteboard => ResourceManager.GetString(nameof(FloatingBar_Whiteboard), _resourceCulture);

        public static string OldUI_Background => ResourceManager.GetString(nameof(OldUI_Background), _resourceCulture);

        public static string OldUI_Check => ResourceManager.GetString(nameof(OldUI_Check), _resourceCulture);

        public static string OldUI_ClearAndHide => ResourceManager.GetString(nameof(OldUI_ClearAndHide), _resourceCulture);

        public static string OldUI_Dark => ResourceManager.GetString(nameof(OldUI_Dark), _resourceCulture);

        public static string OldUI_Exit => ResourceManager.GetString(nameof(OldUI_Exit), _resourceCulture);

        public static string OldUI_HideCanvas => ResourceManager.GetString(nameof(OldUI_HideCanvas), _resourceCulture);

        public static string OldUI_Restore => ResourceManager.GetString(nameof(OldUI_Restore), _resourceCulture);

        public static string OldUI_SingleFingerDrag => ResourceManager.GetString(nameof(OldUI_SingleFingerDrag), _resourceCulture);

        public static string OldUI_SlideshowEnd => ResourceManager.GetString(nameof(OldUI_SlideshowEnd), _resourceCulture);

        public static string OldUI_SlideshowFromStart => ResourceManager.GetString(nameof(OldUI_SlideshowFromStart), _resourceCulture);

        public static string OldUI_Thickness => ResourceManager.GetString(nameof(OldUI_Thickness), _resourceCulture);

        public static string QuickPanel_Exit => ResourceManager.GetString(nameof(QuickPanel_Exit), _resourceCulture);

        public static string QuickPanel_ExitShow => ResourceManager.GetString(nameof(QuickPanel_ExitShow), _resourceCulture);

        public static string QuickPanel_RandomDraw => ResourceManager.GetString(nameof(QuickPanel_RandomDraw), _resourceCulture);

        public static string QuickPanel_Show => ResourceManager.GetString(nameof(QuickPanel_Show), _resourceCulture);

        public static string QuickPanel_SingleDraw => ResourceManager.GetString(nameof(QuickPanel_SingleDraw), _resourceCulture);

        public static string QuickPanel_Timer => ResourceManager.GetString(nameof(QuickPanel_Timer), _resourceCulture);

        public static string QuickPanel_Whiteboard => ResourceManager.GetString(nameof(QuickPanel_Whiteboard), _resourceCulture);

        public static string SnapshotPanel__icstk__png_Hint => ResourceManager.GetString(nameof(SnapshotPanel__icstk__png_Hint), _resourceCulture);

        public static string SnapshotPanel_Hint => ResourceManager.GetString(nameof(SnapshotPanel_Hint), _resourceCulture);

        public static string SnapshotPanel_Hint_1 => ResourceManager.GetString(nameof(SnapshotPanel_Hint_1), _resourceCulture);

        public static string SnapshotPanel_Hint_2 => ResourceManager.GetString(nameof(SnapshotPanel_Hint_2), _resourceCulture);

        public static string SnapshotPanel_Hint_3 => ResourceManager.GetString(nameof(SnapshotPanel_Hint_3), _resourceCulture);

        public static string SnapshotPanel_Hint_4 => ResourceManager.GetString(nameof(SnapshotPanel_Hint_4), _resourceCulture);

        public static string Tools_Manual => ResourceManager.GetString(nameof(Tools_Manual), _resourceCulture);

        public static string Tools_MoreFeaturesTitle => ResourceManager.GetString(nameof(Tools_MoreFeaturesTitle), _resourceCulture);

        public static string Tools_Open => ResourceManager.GetString(nameof(Tools_Open), _resourceCulture);

        public static string Tools_RandomDraw => ResourceManager.GetString(nameof(Tools_RandomDraw), _resourceCulture);

        public static string Tools_Replay => ResourceManager.GetString(nameof(Tools_Replay), _resourceCulture);

        public static string Tools_Save => ResourceManager.GetString(nameof(Tools_Save), _resourceCulture);

        public static string Tools_Screenshot => ResourceManager.GetString(nameof(Tools_Screenshot), _resourceCulture);

        public static string Tools_Settings => ResourceManager.GetString(nameof(Tools_Settings), _resourceCulture);

        public static string Tools_SingleDraw => ResourceManager.GetString(nameof(Tools_SingleDraw), _resourceCulture);

        public static string Tools_Timer => ResourceManager.GetString(nameof(Tools_Timer), _resourceCulture);
    }
}