//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from HomeStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class HomeStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.HomeStrings", typeof(HomeStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Home_ExitApp => ResourceManager.GetString(nameof(Home_ExitApp), _resourceCulture);

        public static string Home_ResetSettings => ResourceManager.GetString(nameof(Home_ResetSettings), _resourceCulture);

        public static string Home_RestartApp => ResourceManager.GetString(nameof(Home_RestartApp), _resourceCulture);

        public static string Splash_Starting => ResourceManager.GetString(nameof(Splash_Starting), _resourceCulture);
    }
}