//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from NavStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class NavStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.NavStrings", typeof(NavStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Nav_About => ResourceManager.GetString(nameof(Nav_About), _resourceCulture);

        public static string Nav_Advanced => ResourceManager.GetString(nameof(Nav_Advanced), _resourceCulture);

        public static string Nav_Advanced_Settings => ResourceManager.GetString(nameof(Nav_Advanced_Settings), _resourceCulture);

        public static string Nav_Automation => ResourceManager.GetString(nameof(Nav_Automation), _resourceCulture);

        public static string Nav_Automation_Settings => ResourceManager.GetString(nameof(Nav_Automation_Settings), _resourceCulture);

        public static string Nav_Canvas => ResourceManager.GetString(nameof(Nav_Canvas), _resourceCulture);

        public static string Nav_CrashAction => ResourceManager.GetString(nameof(Nav_CrashAction), _resourceCulture);

        public static string Nav_FriendlyLinks => ResourceManager.GetString(nameof(Nav_FriendlyLinks), _resourceCulture);

        public static string Nav_Gesture => ResourceManager.GetString(nameof(Nav_Gesture), _resourceCulture);

        public static string Nav_Gesture_Settings => ResourceManager.GetString(nameof(Nav_Gesture_Settings), _resourceCulture);

        public static string Nav_InkRecognition => ResourceManager.GetString(nameof(Nav_InkRecognition), _resourceCulture);

        public static string Nav_Plugins => ResourceManager.GetString(nameof(Nav_Plugins), _resourceCulture);

        public static string Nav_PPT => ResourceManager.GetString(nameof(Nav_PPT), _resourceCulture);

        public static string Nav_PPT_Settings => ResourceManager.GetString(nameof(Nav_PPT_Settings), _resourceCulture);

        public static string Nav_RandomWindow => ResourceManager.GetString(nameof(Nav_RandomWindow), _resourceCulture);

        public static string Nav_RandomWindow_Settings => ResourceManager.GetString(nameof(Nav_RandomWindow_Settings), _resourceCulture);

        public static string Nav_Shortcuts => ResourceManager.GetString(nameof(Nav_Shortcuts), _resourceCulture);

        public static string Nav_Shortcuts_Settings => ResourceManager.GetString(nameof(Nav_Shortcuts_Settings), _resourceCulture);

        public static string Nav_Startup => ResourceManager.GetString(nameof(Nav_Startup), _resourceCulture);

        public static string Nav_Theme => ResourceManager.GetString(nameof(Nav_Theme), _resourceCulture);

        public static string Nav_Theme_Settings => ResourceManager.GetString(nameof(Nav_Theme_Settings), _resourceCulture);

        public static string Settings_AutoSaveHint => ResourceManager.GetString(nameof(Settings_AutoSaveHint), _resourceCulture);

        public static string Settings_Mode => ResourceManager.GetString(nameof(Settings_Mode), _resourceCulture);

        public static string Settings_ModeDesc => ResourceManager.GetString(nameof(Settings_ModeDesc), _resourceCulture);

        public static string Settings_ModeDesc_1 => ResourceManager.GetString(nameof(Settings_ModeDesc_1), _resourceCulture);

        public static string Settings_Nav_Hotkey => ResourceManager.GetString(nameof(Settings_Nav_Hotkey), _resourceCulture);

        public static string Settings_Nav_Hotkey_Tooltip => ResourceManager.GetString(nameof(Settings_Nav_Hotkey_Tooltip), _resourceCulture);

        public static string Settings_Nav_Security => ResourceManager.GetString(nameof(Settings_Nav_Security), _resourceCulture);

        public static string Settings_Nav_Security_Tooltip => ResourceManager.GetString(nameof(Settings_Nav_Security_Tooltip), _resourceCulture);

        public static string Settings_NewWindow => ResourceManager.GetString(nameof(Settings_NewWindow), _resourceCulture);

        public static string Settings_NewWindowDesc => ResourceManager.GetString(nameof(Settings_NewWindowDesc), _resourceCulture);

        public static string Settings_Plugins => ResourceManager.GetString(nameof(Settings_Plugins), _resourceCulture);

        public static string Settings_PluginsDesc => ResourceManager.GetString(nameof(Settings_PluginsDesc), _resourceCulture);

        public static string Settings_Title => ResourceManager.GetString(nameof(Settings_Title), _resourceCulture);
    }
}