//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from RandomStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class RandomStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.RandomStrings", typeof(RandomStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string LuckyRandomPanel_Hint => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint), _resourceCulture);

        public static string LuckyRandomPanel_Hint_1 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_1), _resourceCulture);

        public static string LuckyRandomPanel_Hint_10 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_10), _resourceCulture);

        public static string LuckyRandomPanel_Hint_2 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_2), _resourceCulture);

        public static string LuckyRandomPanel_Hint_3 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_3), _resourceCulture);

        public static string LuckyRandomPanel_Hint_4 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_4), _resourceCulture);

        public static string LuckyRandomPanel_Hint_5 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_5), _resourceCulture);

        public static string LuckyRandomPanel_Hint_6 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_6), _resourceCulture);

        public static string LuckyRandomPanel_Hint_7 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_7), _resourceCulture);

        public static string LuckyRandomPanel_Hint_8 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_8), _resourceCulture);

        public static string LuckyRandomPanel_Hint_9 => ResourceManager.GetString(nameof(LuckyRandomPanel_Hint_9), _resourceCulture);

        public static string Random_Background_Default => ResourceManager.GetString(nameof(Random_Background_Default), _resourceCulture);

        public static string Random_BackgroundSelectLabel => ResourceManager.GetString(nameof(Random_BackgroundSelectLabel), _resourceCulture);

        public static string Random_BackgroundSettingsTitle => ResourceManager.GetString(nameof(Random_BackgroundSettingsTitle), _resourceCulture);

        public static string Random_CustomBackground_Manage => ResourceManager.GetString(nameof(Random_CustomBackground_Manage), _resourceCulture);

        public static string Random_CustomBackground_Upload => ResourceManager.GetString(nameof(Random_CustomBackground_Upload), _resourceCulture);

        public static string Random_CustomBackgroundLabel => ResourceManager.GetString(nameof(Random_CustomBackgroundLabel), _resourceCulture);

        public static string Random_EnableButtons => ResourceManager.GetString(nameof(Random_EnableButtons), _resourceCulture);

        public static string Random_EnableQuickButton => ResourceManager.GetString(nameof(Random_EnableQuickButton), _resourceCulture);

        public static string Random_ExternalType_ClassIsland => ResourceManager.GetString(nameof(Random_ExternalType_ClassIsland), _resourceCulture);

        public static string Random_ExternalType_NamePicker => ResourceManager.GetString(nameof(Random_ExternalType_NamePicker), _resourceCulture);

        public static string Random_ExternalType_SecRandom => ResourceManager.GetString(nameof(Random_ExternalType_SecRandom), _resourceCulture);

        public static string Random_ExternalTypeLabel => ResourceManager.GetString(nameof(Random_ExternalTypeLabel), _resourceCulture);

        public static string Random_ML_AvoidRepeat => ResourceManager.GetString(nameof(Random_ML_AvoidRepeat), _resourceCulture);

        public static string Random_ML_Hint => ResourceManager.GetString(nameof(Random_ML_Hint), _resourceCulture);

        public static string Random_ML_HistoryCount => ResourceManager.GetString(nameof(Random_ML_HistoryCount), _resourceCulture);

        public static string Random_ML_Weight => ResourceManager.GetString(nameof(Random_ML_Weight), _resourceCulture);

        public static string Random_NewUI_Enable => ResourceManager.GetString(nameof(Random_NewUI_Enable), _resourceCulture);

        public static string Random_NewUI_Title => ResourceManager.GetString(nameof(Random_NewUI_Title), _resourceCulture);

        public static string Random_OnceCloseDelay => ResourceManager.GetString(nameof(Random_OnceCloseDelay), _resourceCulture);

        public static string Random_OnceMaxStudents => ResourceManager.GetString(nameof(Random_OnceMaxStudents), _resourceCulture);

        public static string Random_ShowEditNamesButton => ResourceManager.GetString(nameof(Random_ShowEditNamesButton), _resourceCulture);

        public static string Random_Title => ResourceManager.GetString(nameof(Random_Title), _resourceCulture);

        public static string Random_UseExternal => ResourceManager.GetString(nameof(Random_UseExternal), _resourceCulture);

        public static string Random_SelectTimerAlarm => ResourceManager.GetString(nameof(Random_SelectTimerAlarm), _resourceCulture);

        public static string Random_AudioFilter => ResourceManager.GetString(nameof(Random_AudioFilter), _resourceCulture);

        public static string Random_CustomAlarmSuccess => ResourceManager.GetString(nameof(Random_CustomAlarmSuccess), _resourceCulture);

        public static string Random_AlarmSetupSuccess => ResourceManager.GetString(nameof(Random_AlarmSetupSuccess), _resourceCulture);

        public static string Random_ResetAlarmSuccess => ResourceManager.GetString(nameof(Random_ResetAlarmSuccess), _resourceCulture);

        public static string Random_ResetSuccess => ResourceManager.GetString(nameof(Random_ResetSuccess), _resourceCulture);

        public static string Random_SelectProgressiveAlarm => ResourceManager.GetString(nameof(Random_SelectProgressiveAlarm), _resourceCulture);
    }
}