//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from SecurityStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class SecurityStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.SecurityStrings", typeof(SecurityStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string FileAssoc_Check => ResourceManager.GetString(nameof(FileAssoc_Check), _resourceCulture);

        public static string FileAssoc_Desc => ResourceManager.GetString(nameof(FileAssoc_Desc), _resourceCulture);

        public static string FileAssoc_Register => ResourceManager.GetString(nameof(FileAssoc_Register), _resourceCulture);

        public static string FileAssoc_Title => ResourceManager.GetString(nameof(FileAssoc_Title), _resourceCulture);

        public static string FileAssoc_Unregister => ResourceManager.GetString(nameof(FileAssoc_Unregister), _resourceCulture);

        public static string SecurityPanel__InkCanvasForClass_Hint => ResourceManager.GetString(nameof(SecurityPanel__InkCanvasForClass_Hint), _resourceCulture);

        public static string SecurityPanel__Settingsjson_Hint => ResourceManager.GetString(nameof(SecurityPanel__Settingsjson_Hint), _resourceCulture);

        public static string SecurityPanel_Hint => ResourceManager.GetString(nameof(SecurityPanel_Hint), _resourceCulture);

        public static string SecurityPanel_Hint_1 => ResourceManager.GetString(nameof(SecurityPanel_Hint_1), _resourceCulture);

        public static string SecurityPanel_Hint_2 => ResourceManager.GetString(nameof(SecurityPanel_Hint_2), _resourceCulture);

        public static string SecurityPanel_Hint_3 => ResourceManager.GetString(nameof(SecurityPanel_Hint_3), _resourceCulture);

        public static string SecurityPanel_Hint_4 => ResourceManager.GetString(nameof(SecurityPanel_Hint_4), _resourceCulture);

        public static string SettingsBaseView_Binding_DescriptionHint => ResourceManager.GetString(nameof(SettingsBaseView_Binding_DescriptionHint), _resourceCulture);

        public static string Tooltip_IccProtocol => ResourceManager.GetString(nameof(Tooltip_IccProtocol), _resourceCulture);
    }
}