//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from StartupStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class StartupStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.StartupStrings", typeof(StartupStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Channel_Beta => ResourceManager.GetString(nameof(Channel_Beta), _resourceCulture);

        public static string Channel_Hint => ResourceManager.GetString(nameof(Channel_Hint), _resourceCulture);

        public static string Channel_Preview => ResourceManager.GetString(nameof(Channel_Preview), _resourceCulture);

        public static string Channel_Release => ResourceManager.GetString(nameof(Channel_Release), _resourceCulture);

        public static string ManualUpdate_Hint => ResourceManager.GetString(nameof(ManualUpdate_Hint), _resourceCulture);

        public static string Rollback_Hint => ResourceManager.GetString(nameof(Rollback_Hint), _resourceCulture);

        public static string SilentUpdate_AfterDownloadHint => ResourceManager.GetString(nameof(SilentUpdate_AfterDownloadHint), _resourceCulture);

        public static string SilentUpdate_Hint => ResourceManager.GetString(nameof(SilentUpdate_Hint), _resourceCulture);

        public static string SilentUpdate_TimeRange => ResourceManager.GetString(nameof(SilentUpdate_TimeRange), _resourceCulture);

        public static string AutoUpdateHint => ResourceManager.GetString(nameof(AutoUpdateHint), _resourceCulture);

        public static string EnableNibMode => ResourceManager.GetString(nameof(EnableNibMode), _resourceCulture);

        public static string EnableNibModeHint => ResourceManager.GetString(nameof(EnableNibModeHint), _resourceCulture);

        public static string EndTime => ResourceManager.GetString(nameof(EndTime), _resourceCulture);

        public static string ExternalProtocol => ResourceManager.GetString(nameof(ExternalProtocol), _resourceCulture);

        public static string ExternalProtocolHint => ResourceManager.GetString(nameof(ExternalProtocolHint), _resourceCulture);

        public static string FixVersionHint => ResourceManager.GetString(nameof(FixVersionHint), _resourceCulture);

        public static string FoldAtStartup => ResourceManager.GetString(nameof(FoldAtStartup), _resourceCulture);

        public static string FoldAtStartupHint => ResourceManager.GetString(nameof(FoldAtStartupHint), _resourceCulture);

        public static string HistoryRollbackHint => ResourceManager.GetString(nameof(HistoryRollbackHint), _resourceCulture);

        public static string ManualUpdateHint => ResourceManager.GetString(nameof(ManualUpdateHint), _resourceCulture);

        public static string MinimizeToSidebar => ResourceManager.GetString(nameof(MinimizeToSidebar), _resourceCulture);

        public static string NoBorderMode => ResourceManager.GetString(nameof(NoBorderMode), _resourceCulture);

        public static string NoBorderModeHint => ResourceManager.GetString(nameof(NoBorderModeHint), _resourceCulture);

        public static string NoFocusMode => ResourceManager.GetString(nameof(NoFocusMode), _resourceCulture);

        public static string NoFocusModeHint => ResourceManager.GetString(nameof(NoFocusModeHint), _resourceCulture);

        public static string PPTOnlyModeHint => ResourceManager.GetString(nameof(PPTOnlyModeHint), _resourceCulture);

        public static string RunAtLogin => ResourceManager.GetString(nameof(RunAtLogin), _resourceCulture);

        public static string RunAtStartup => ResourceManager.GetString(nameof(RunAtStartup), _resourceCulture);

        public static string RunAtStartupHint => ResourceManager.GetString(nameof(RunAtStartupHint), _resourceCulture);

        public static string SilentUpdateFullHint => ResourceManager.GetString(nameof(SilentUpdateFullHint), _resourceCulture);

        public static string SilentUpdateHint => ResourceManager.GetString(nameof(SilentUpdateHint), _resourceCulture);

        public static string SilentUpdateTimePeriod => ResourceManager.GetString(nameof(SilentUpdateTimePeriod), _resourceCulture);

        public static string SmartUpdate => ResourceManager.GetString(nameof(SmartUpdate), _resourceCulture);

        public static string SmartUpdateHint => ResourceManager.GetString(nameof(SmartUpdateHint), _resourceCulture);

        public static string Start => ResourceManager.GetString(nameof(Start), _resourceCulture);

        public static string StartTime => ResourceManager.GetString(nameof(StartTime), _resourceCulture);

        public static string TimePeriodHint => ResourceManager.GetString(nameof(TimePeriodHint), _resourceCulture);

        public static string TopMost => ResourceManager.GetString(nameof(TopMost), _resourceCulture);

        public static string TopMostHint => ResourceManager.GetString(nameof(TopMostHint), _resourceCulture);

        public static string TopMostMode => ResourceManager.GetString(nameof(TopMostMode), _resourceCulture);

        public static string TopMostMode_Normal => ResourceManager.GetString(nameof(TopMostMode_Normal), _resourceCulture);

        public static string TopMostMode_Normal_RestartRequired => ResourceManager.GetString(nameof(TopMostMode_Normal_RestartRequired), _resourceCulture);

        public static string TopMostMode_RestartAsAdmin => ResourceManager.GetString(nameof(TopMostMode_RestartAsAdmin), _resourceCulture);

        public static string TopMostMode_CurrentUIAccessNormal => ResourceManager.GetString(nameof(TopMostMode_CurrentUIAccessNormal), _resourceCulture);

        public static string TopMostMode_RestartAsNormal => ResourceManager.GetString(nameof(TopMostMode_RestartAsNormal), _resourceCulture);

        public static string TopMostMode_UIA => ResourceManager.GetString(nameof(TopMostMode_UIA), _resourceCulture);

        public static string TopMostMode_UIA_RestartRequired => ResourceManager.GetString(nameof(TopMostMode_UIA_RestartRequired), _resourceCulture);

        public static string UIAccessTopMostHint => ResourceManager.GetString(nameof(UIAccessTopMostHint), _resourceCulture);

        public static string UIAccessTopMostHint_1 => ResourceManager.GetString(nameof(UIAccessTopMostHint_1), _resourceCulture);

        public static string UIATopMost => ResourceManager.GetString(nameof(UIATopMost), _resourceCulture);

        public static string UIATopMostHint => ResourceManager.GetString(nameof(UIATopMostHint), _resourceCulture);

        public static string UpdateChannel => ResourceManager.GetString(nameof(UpdateChannel), _resourceCulture);

        public static string UpdateChannelHint => ResourceManager.GetString(nameof(UpdateChannelHint), _resourceCulture);

        public static string UpdatePackageArchitecture => ResourceManager.GetString(nameof(UpdatePackageArchitecture), _resourceCulture);

        public static string UpdatePackageArchitectureHint => ResourceManager.GetString(nameof(UpdatePackageArchitectureHint), _resourceCulture);

        public static string VersionFix_Hint => ResourceManager.GetString(nameof(VersionFix_Hint), _resourceCulture);
    }
}