//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from ThemeStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class ThemeStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.ThemeStrings", typeof(ThemeStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string AppearancePanel_24HourTimeFormat => ResourceManager.GetString(nameof(AppearancePanel_24HourTimeFormat), _resourceCulture);

        public static string AppearancePanel_80Hint => ResourceManager.GetString(nameof(AppearancePanel_80Hint), _resourceCulture);

        public static string AppearancePanel_Hint => ResourceManager.GetString(nameof(AppearancePanel_Hint), _resourceCulture);

        public static string AppearancePanel_Hint_ShowStartupAnimation => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowStartupAnimation), _resourceCulture);

        public static string AppearancePanel_Hint_ShowRedoButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowRedoButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowClearButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowClearButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowWhiteboardButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowWhiteboardButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowHideButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowHideButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowLassoSelectButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowLassoSelectButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowClearAndMouseButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowClearAndMouseButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowQuickPalette => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowQuickPalette), _resourceCulture);

        public static string AppearancePanel_Hint_SelectQuickPaletteMode => ResourceManager.GetString(nameof(AppearancePanel_Hint_SelectQuickPaletteMode), _resourceCulture);

        public static string AppearancePanel_Hint_ShowTrayIcon => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowTrayIcon), _resourceCulture);

        public static string AppearancePanel_Hint_ShowTimeAndDate => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowTimeAndDate), _resourceCulture);

        public static string AppearancePanel_Hint_SelectAnimationStyle => ResourceManager.GetString(nameof(AppearancePanel_Hint_SelectAnimationStyle), _resourceCulture);

        public static string AppearancePanel_Hint_ShowMotivationalQuotes => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowMotivationalQuotes), _resourceCulture);

        public static string AppearancePanel_Hint_ShowQuickActionsInCollapsed => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowQuickActionsInCollapsed), _resourceCulture);

        public static string AppearancePanel_Hint_SelectUncollapseIconStyle => ResourceManager.GetString(nameof(AppearancePanel_Hint_SelectUncollapseIconStyle), _resourceCulture);

        public static string AppearancePanel_Hint_AutoAnnotateOnUncollapse => ResourceManager.GetString(nameof(AppearancePanel_Hint_AutoAnnotateOnUncollapse), _resourceCulture);

        public static string AppearancePanel_Hint_AutoCollapseOnWhiteboardExit => ResourceManager.GetString(nameof(AppearancePanel_Hint_AutoCollapseOnWhiteboardExit), _resourceCulture);

        public static string AppearancePanel_Hint_SelectToolbarIconStyle => ResourceManager.GetString(nameof(AppearancePanel_Hint_SelectToolbarIconStyle), _resourceCulture);

        public static string AppearancePanel_Hint_AdjustToolbarSize => ResourceManager.GetString(nameof(AppearancePanel_Hint_AdjustToolbarSize), _resourceCulture);

        public static string AppearancePanel_Hint_AdjustToolbarOpacity => ResourceManager.GetString(nameof(AppearancePanel_Hint_AdjustToolbarOpacity), _resourceCulture);

        public static string AppearancePanel_Hint_ShowPenTipModeButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowPenTipModeButton), _resourceCulture);

        public static string AppearancePanel_Hint_UseLegacyToolbarStyle => ResourceManager.GetString(nameof(AppearancePanel_Hint_UseLegacyToolbarStyle), _resourceCulture);

        public static string AppearancePanel_Hint_ShowShapeButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowShapeButton), _resourceCulture);

        public static string AppearancePanel_Hint_ShowUndoButton => ResourceManager.GetString(nameof(AppearancePanel_Hint_ShowUndoButton), _resourceCulture);

        public static string AppearancePanel_PPTHint => ResourceManager.GetString(nameof(AppearancePanel_PPTHint), _resourceCulture);

        public static string AppearancePanel_PPTPPTHint => ResourceManager.GetString(nameof(AppearancePanel_PPTPPTHint), _resourceCulture);

        public static string Theme_BlackboardScale80 => ResourceManager.GetString(nameof(Theme_BlackboardScale80), _resourceCulture);

        public static string Theme_Browse => ResourceManager.GetString(nameof(Theme_Browse), _resourceCulture);

        public static string Theme_Clear => ResourceManager.GetString(nameof(Theme_Clear), _resourceCulture);

        public static string Theme_CustomFloatingIconLabel => ResourceManager.GetString(nameof(Theme_CustomFloatingIconLabel), _resourceCulture);

        public static string Theme_Customize => ResourceManager.GetString(nameof(Theme_Customize), _resourceCulture);

        public static string Theme_CustomSplash_NotSelected => ResourceManager.GetString(nameof(Theme_CustomSplash_NotSelected), _resourceCulture);

        public static string Theme_CustomSplashImage => ResourceManager.GetString(nameof(Theme_CustomSplashImage), _resourceCulture);

        public static string Theme_CustomSplashImage_Desc => ResourceManager.GetString(nameof(Theme_CustomSplashImage_Desc), _resourceCulture);

        public static string Theme_CustomSplashTextPosition => ResourceManager.GetString(nameof(Theme_CustomSplashTextPosition), _resourceCulture);

        public static string Theme_CustomSplashTextPosition_Desc => ResourceManager.GetString(nameof(Theme_CustomSplashTextPosition_Desc), _resourceCulture);

        public static string Theme_Dark => ResourceManager.GetString(nameof(Theme_Dark), _resourceCulture);

        public static string Theme_EnableQuickPanel => ResourceManager.GetString(nameof(Theme_EnableQuickPanel), _resourceCulture);

        public static string Theme_EnableSplash => ResourceManager.GetString(nameof(Theme_EnableSplash), _resourceCulture);

        public static string Theme_EraserButtonDisplay => ResourceManager.GetString(nameof(Theme_EraserButtonDisplay), _resourceCulture);

        public static string Theme_EraserDisplay_AreaOnly => ResourceManager.GetString(nameof(Theme_EraserDisplay_AreaOnly), _resourceCulture);

        public static string Theme_EraserDisplay_Both => ResourceManager.GetString(nameof(Theme_EraserDisplay_Both), _resourceCulture);

        public static string Theme_EraserDisplay_LineOnly => ResourceManager.GetString(nameof(Theme_EraserDisplay_LineOnly), _resourceCulture);

        public static string Theme_EraserDisplay_None => ResourceManager.GetString(nameof(Theme_EraserDisplay_None), _resourceCulture);

        public static string Theme_FloatingBarButtonsTitle => ResourceManager.GetString(nameof(Theme_FloatingBarButtonsTitle), _resourceCulture);

        public static string Theme_FloatingBarIcon => ResourceManager.GetString(nameof(Theme_FloatingBarIcon), _resourceCulture);

        public static string Theme_FloatingBarOpacity => ResourceManager.GetString(nameof(Theme_FloatingBarOpacity), _resourceCulture);

        public static string Theme_FloatingBarOpacityInPPT => ResourceManager.GetString(nameof(Theme_FloatingBarOpacityInPPT), _resourceCulture);

        public static string Theme_FloatingBarOpacityInPPTHint => ResourceManager.GetString(nameof(Theme_FloatingBarOpacityInPPTHint), _resourceCulture);

        public static string Theme_FloatingBarScale => ResourceManager.GetString(nameof(Theme_FloatingBarScale), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkAbused => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkAbused), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkCrossEye => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkCrossEye), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkGreenHatDoge => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkGreenHatDoge), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkSmile => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkSmile), _resourceCulture);

        public static string Theme_FloatingIcon_CoolapkUnderwear => ResourceManager.GetString(nameof(Theme_FloatingIcon_CoolapkUnderwear), _resourceCulture);

        public static string Theme_FloatingIcon_IccBlackTransparent => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccBlackTransparent), _resourceCulture);

        public static string Theme_FloatingIcon_IccDark => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccDark), _resourceCulture);

        public static string Theme_FloatingIcon_IccDarkBreath => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccDarkBreath), _resourceCulture);

        public static string Theme_FloatingIcon_IccDefault => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccDefault), _resourceCulture);

        public static string Theme_FloatingIcon_IccNoShadow => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccNoShadow), _resourceCulture);

        public static string Theme_FloatingIcon_IccWhiteTransparent => ResourceManager.GetString(nameof(Theme_FloatingIcon_IccWhiteTransparent), _resourceCulture);

        public static string Theme_FloatingIcon_TiebaEmoji => ResourceManager.GetString(nameof(Theme_FloatingIcon_TiebaEmoji), _resourceCulture);

        public static string Theme_GroupTitle => ResourceManager.GetString(nameof(Theme_GroupTitle), _resourceCulture);

        public static string Theme_Label => ResourceManager.GetString(nameof(Theme_Label), _resourceCulture);

        public static string Theme_Language_ChineseSimplified => ResourceManager.GetString(nameof(Theme_Language_ChineseSimplified), _resourceCulture);

        public static string Theme_Language_English => ResourceManager.GetString(nameof(Theme_Language_English), _resourceCulture);

        public static string Theme_Language_RestartHint => ResourceManager.GetString(nameof(Theme_Language_RestartHint), _resourceCulture);

        public static string Theme_Language_System => ResourceManager.GetString(nameof(Theme_Language_System), _resourceCulture);

        public static string Theme_LanguageLabel => ResourceManager.GetString(nameof(Theme_LanguageLabel), _resourceCulture);

        public static string Theme_Light => ResourceManager.GetString(nameof(Theme_Light), _resourceCulture);

        public static string Theme_Manage => ResourceManager.GetString(nameof(Theme_Manage), _resourceCulture);

        public static string Theme_QuickPalette_DoubleRow => ResourceManager.GetString(nameof(Theme_QuickPalette_DoubleRow), _resourceCulture);

        public static string Theme_QuickPalette_SingleRow => ResourceManager.GetString(nameof(Theme_QuickPalette_SingleRow), _resourceCulture);

        public static string Theme_QuickPaletteMode => ResourceManager.GetString(nameof(Theme_QuickPaletteMode), _resourceCulture);

        public static string Theme_QuickPanelBottomOffset => ResourceManager.GetString(nameof(Theme_QuickPanelBottomOffset), _resourceCulture);

        public static string Theme_QuoteSource => ResourceManager.GetString(nameof(Theme_QuoteSource), _resourceCulture);

        public static string Theme_QuoteSource_GaokaoBless => ResourceManager.GetString(nameof(Theme_QuoteSource_GaokaoBless), _resourceCulture);

        public static string Theme_QuoteSource_Hitokoto => ResourceManager.GetString(nameof(Theme_QuoteSource_Hitokoto), _resourceCulture);

        public static string Theme_QuoteSource_Mottos => ResourceManager.GetString(nameof(Theme_QuoteSource_Mottos), _resourceCulture);

        public static string Theme_QuoteSource_OsuQuotes => ResourceManager.GetString(nameof(Theme_QuoteSource_OsuQuotes), _resourceCulture);

        public static string Theme_QuoteSource_PhigrosTips => ResourceManager.GetString(nameof(Theme_QuoteSource_PhigrosTips), _resourceCulture);

        public static string Theme_ShowClearAndMouseButton => ResourceManager.GetString(nameof(Theme_ShowClearAndMouseButton), _resourceCulture);

        public static string Theme_ShowClearButton => ResourceManager.GetString(nameof(Theme_ShowClearButton), _resourceCulture);

        public static string Theme_ShowHideButton => ResourceManager.GetString(nameof(Theme_ShowHideButton), _resourceCulture);

        public static string Theme_ShowLassoButton => ResourceManager.GetString(nameof(Theme_ShowLassoButton), _resourceCulture);

        public static string Theme_ShowNibButton => ResourceManager.GetString(nameof(Theme_ShowNibButton), _resourceCulture);

        public static string Theme_ShowQuickPalette => ResourceManager.GetString(nameof(Theme_ShowQuickPalette), _resourceCulture);

        public static string Theme_ShowQuoteInWhiteboard => ResourceManager.GetString(nameof(Theme_ShowQuoteInWhiteboard), _resourceCulture);

        public static string Theme_ShowRedoButton => ResourceManager.GetString(nameof(Theme_ShowRedoButton), _resourceCulture);

        public static string Theme_ShowShapeButton => ResourceManager.GetString(nameof(Theme_ShowShapeButton), _resourceCulture);

        public static string Theme_ShowTimeInWhiteboard => ResourceManager.GetString(nameof(Theme_ShowTimeInWhiteboard), _resourceCulture);

        public static string Theme_ShowUndoButton => ResourceManager.GetString(nameof(Theme_ShowUndoButton), _resourceCulture);

        public static string Theme_ShowWhiteboardButton => ResourceManager.GetString(nameof(Theme_ShowWhiteboardButton), _resourceCulture);

        public static string Theme_Splash_Autumn => ResourceManager.GetString(nameof(Theme_Splash_Autumn), _resourceCulture);

        public static string Theme_Splash_Custom => ResourceManager.GetString(nameof(Theme_Splash_Custom), _resourceCulture);

        public static string Theme_Splash_Horse => ResourceManager.GetString(nameof(Theme_Splash_Horse), _resourceCulture);

        public static string Theme_Splash_Random => ResourceManager.GetString(nameof(Theme_Splash_Random), _resourceCulture);

        public static string Theme_Splash_Seasonal => ResourceManager.GetString(nameof(Theme_Splash_Seasonal), _resourceCulture);

        public static string Theme_Splash_Spring => ResourceManager.GetString(nameof(Theme_Splash_Spring), _resourceCulture);

        public static string Theme_Splash_Summer => ResourceManager.GetString(nameof(Theme_Splash_Summer), _resourceCulture);

        public static string Theme_Splash_Winter => ResourceManager.GetString(nameof(Theme_Splash_Winter), _resourceCulture);

        public static string Theme_SplashStyle => ResourceManager.GetString(nameof(Theme_SplashStyle), _resourceCulture);

        public static string Theme_System => ResourceManager.GetString(nameof(Theme_System), _resourceCulture);

        public static string Theme_TextPosition_BottomCenter => ResourceManager.GetString(nameof(Theme_TextPosition_BottomCenter), _resourceCulture);

        public static string Theme_TextPosition_BottomLeft => ResourceManager.GetString(nameof(Theme_TextPosition_BottomLeft), _resourceCulture);

        public static string Theme_TextPosition_BottomRight => ResourceManager.GetString(nameof(Theme_TextPosition_BottomRight), _resourceCulture);

        public static string Theme_UnfoldButtonIcon => ResourceManager.GetString(nameof(Theme_UnfoldButtonIcon), _resourceCulture);

        public static string Theme_UnfoldIcon_Arrow => ResourceManager.GetString(nameof(Theme_UnfoldIcon_Arrow), _resourceCulture);

        public static string Theme_UnfoldIcon_Pen => ResourceManager.GetString(nameof(Theme_UnfoldIcon_Pen), _resourceCulture);

        public static string Theme_Upload => ResourceManager.GetString(nameof(Theme_Upload), _resourceCulture);

        public static string Theme_UseLegacyFloatingBarUI => ResourceManager.GetString(nameof(Theme_UseLegacyFloatingBarUI), _resourceCulture);

        public static string Theme_WindowBackdrop => ResourceManager.GetString(nameof(Theme_WindowBackdrop), _resourceCulture);

        public static string Theme_WindowBackdrop_Acrylic => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Acrylic), _resourceCulture);

        public static string Theme_WindowBackdrop_Acrylic10 => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Acrylic10), _resourceCulture);

        public static string Theme_WindowBackdrop_Acrylic11 => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Acrylic11), _resourceCulture);

        public static string Theme_WindowBackdrop_Description => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Description), _resourceCulture);

        public static string Theme_WindowBackdrop_Mica => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Mica), _resourceCulture);

        public static string Theme_WindowBackdrop_None => ResourceManager.GetString(nameof(Theme_WindowBackdrop_None), _resourceCulture);

        public static string Theme_WindowBackdrop_Tabbed => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Tabbed), _resourceCulture);

        public static string Theme_WindowBackdrop_Transient => ResourceManager.GetString(nameof(Theme_WindowBackdrop_Transient), _resourceCulture);

        public static string ThemePanel_80Hint => ResourceManager.GetString(nameof(ThemePanel_80Hint), _resourceCulture);

        public static string ThemePanel_Hint => ResourceManager.GetString(nameof(ThemePanel_Hint), _resourceCulture);

        public static string ThemePanel_Hint_ShowStartupAnimation => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowStartupAnimation), _resourceCulture);

        public static string ThemePanel_Hint_ShowRedoButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowRedoButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowClearButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowClearButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowWhiteboardButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowWhiteboardButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowHideButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowHideButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowLassoSelectButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowLassoSelectButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowClearAndMouseButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowClearAndMouseButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowQuickPalette => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowQuickPalette), _resourceCulture);

        public static string ThemePanel_Hint_SelectQuickPaletteMode => ResourceManager.GetString(nameof(ThemePanel_Hint_SelectQuickPaletteMode), _resourceCulture);

        public static string ThemePanel_Hint_ShowTrayIcon => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowTrayIcon), _resourceCulture);

        public static string ThemePanel_Hint_ShowTimeAndDate => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowTimeAndDate), _resourceCulture);

        public static string ThemePanel_Hint_SelectAnimationStyle => ResourceManager.GetString(nameof(ThemePanel_Hint_SelectAnimationStyle), _resourceCulture);

        public static string ThemePanel_Hint_ShowMotivationalQuotes => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowMotivationalQuotes), _resourceCulture);

        public static string ThemePanel_Hint_ShowQuickActionsInCollapsed => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowQuickActionsInCollapsed), _resourceCulture);

        public static string ThemePanel_Hint_SelectUncollapseIconStyle => ResourceManager.GetString(nameof(ThemePanel_Hint_SelectUncollapseIconStyle), _resourceCulture);

        public static string ThemePanel_Hint_AutoAnnotateOnUncollapse => ResourceManager.GetString(nameof(ThemePanel_Hint_AutoAnnotateOnUncollapse), _resourceCulture);

        public static string ThemePanel_Hint_AutoCollapseOnWhiteboardExit => ResourceManager.GetString(nameof(ThemePanel_Hint_AutoCollapseOnWhiteboardExit), _resourceCulture);

        public static string ThemePanel_Hint_SelectToolbarIconStyle => ResourceManager.GetString(nameof(ThemePanel_Hint_SelectToolbarIconStyle), _resourceCulture);

        public static string ThemePanel_Hint_AdjustToolbarSize => ResourceManager.GetString(nameof(ThemePanel_Hint_AdjustToolbarSize), _resourceCulture);

        public static string ThemePanel_Hint_AdjustToolbarOpacity => ResourceManager.GetString(nameof(ThemePanel_Hint_AdjustToolbarOpacity), _resourceCulture);

        public static string ThemePanel_Hint_ShowPenTipModeButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowPenTipModeButton), _resourceCulture);

        public static string ThemePanel_Hint_UseLegacyToolbarStyle => ResourceManager.GetString(nameof(ThemePanel_Hint_UseLegacyToolbarStyle), _resourceCulture);

        public static string ThemePanel_Hint_ShowShapeButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowShapeButton), _resourceCulture);

        public static string ThemePanel_Hint_ShowUndoButton => ResourceManager.GetString(nameof(ThemePanel_Hint_ShowUndoButton), _resourceCulture);

        public static string ThemePanel_PPTHint => ResourceManager.GetString(nameof(ThemePanel_PPTHint), _resourceCulture);

        public static string ThemePanel_PPTPPTHint => ResourceManager.GetString(nameof(ThemePanel_PPTPPTHint), _resourceCulture);
    }
}