//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from TimerStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class TimerStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.TimerStrings", typeof(TimerStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Timer_CustomSoundLabel => ResourceManager.GetString(nameof(Timer_CustomSoundLabel), _resourceCulture);

        public static string Timer_EnableCountUp => ResourceManager.GetString(nameof(Timer_EnableCountUp), _resourceCulture);

        public static string Timer_NewUI => ResourceManager.GetString(nameof(Timer_NewUI), _resourceCulture);

        public static string Timer_OvertimeHighlight => ResourceManager.GetString(nameof(Timer_OvertimeHighlight), _resourceCulture);

        public static string Timer_Progressive => ResourceManager.GetString(nameof(Timer_Progressive), _resourceCulture);

        public static string Timer_ProgressiveCustomLabel => ResourceManager.GetString(nameof(Timer_ProgressiveCustomLabel), _resourceCulture);

        public static string Timer_ProgressiveSelectFile => ResourceManager.GetString(nameof(Timer_ProgressiveSelectFile), _resourceCulture);

        public static string Timer_ProgressiveVolume => ResourceManager.GetString(nameof(Timer_ProgressiveVolume), _resourceCulture);

        public static string Timer_Reset => ResourceManager.GetString(nameof(Timer_Reset), _resourceCulture);

        public static string Timer_Title => ResourceManager.GetString(nameof(Timer_Title), _resourceCulture);

        public static string Timer_UseLegacyButtons => ResourceManager.GetString(nameof(Timer_UseLegacyButtons), _resourceCulture);

        public static string Timer_Volume => ResourceManager.GetString(nameof(Timer_Volume), _resourceCulture);
    }
}