//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from UpdateCenterPanelStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class UpdateCenterPanelStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.UpdateCenterPanelStrings", typeof(UpdateCenterPanelStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string UpdateCenterPanel_Hint => ResourceManager.GetString(nameof(UpdateCenterPanel_Hint), _resourceCulture);

        public static string UpdateCenterPanel_Hint_1 => ResourceManager.GetString(nameof(UpdateCenterPanel_Hint_1), _resourceCulture);

        public static string UpdateCenterPanel_Hint_2 => ResourceManager.GetString(nameof(UpdateCenterPanel_Hint_2), _resourceCulture);

        public static string UpdateCenterPanel_Hint_3 => ResourceManager.GetString(nameof(UpdateCenterPanel_Hint_3), _resourceCulture);

        public static string UpdateCenterPanel_Hint_4 => ResourceManager.GetString(nameof(UpdateCenterPanel_Hint_4), _resourceCulture);
    }
}