//------------------------------------------------------------------------------
// <auto-generated>
//     Generated from UpdateStrings.resx, do not edit manually.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Ink_Canvas.Properties
{
    [CompilerGenerated]
    public static class UpdateStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Ink_Canvas.Properties.UpdateStrings", typeof(UpdateStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        public static CultureInfo Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string GetString(string key)
        {
            return ResourceManager.GetString(key, _resourceCulture);
        }

        public static string Header_AutoUpdate => ResourceManager.GetString(nameof(Header_AutoUpdate), _resourceCulture);

        public static string Header_SilentUpdate => ResourceManager.GetString(nameof(Header_SilentUpdate), _resourceCulture);

        public static string Msg_DownloadFailedTitle => ResourceManager.GetString(nameof(Msg_DownloadFailedTitle), _resourceCulture);

        public static string Msg_RestartLimit => ResourceManager.GetString(nameof(Msg_RestartLimit), _resourceCulture);

        public static string Msg_RestartLimitTitle => ResourceManager.GetString(nameof(Msg_RestartLimitTitle), _resourceCulture);

        public static string Msg_SkipVersion => ResourceManager.GetString(nameof(Msg_SkipVersion), _resourceCulture);

        public static string Msg_SkipVersionTitle => ResourceManager.GetString(nameof(Msg_SkipVersionTitle), _resourceCulture);

        public static string Msg_UnexpectedError => ResourceManager.GetString(nameof(Msg_UnexpectedError), _resourceCulture);

        public static string Msg_UpdateDownloadFailed => ResourceManager.GetString(nameof(Msg_UpdateDownloadFailed), _resourceCulture);

        public static string Msg_UpdateReady => ResourceManager.GetString(nameof(Msg_UpdateReady), _resourceCulture);

        public static string Msg_UpdateReadyTitle => ResourceManager.GetString(nameof(Msg_UpdateReadyTitle), _resourceCulture);

        public static string Update_Beta => ResourceManager.GetString(nameof(Update_Beta), _resourceCulture);

        public static string Update_Channel => ResourceManager.GetString(nameof(Update_Channel), _resourceCulture);

        public static string Update_PackageArch_X64 => ResourceManager.GetString(nameof(Update_PackageArch_X64), _resourceCulture);

        public static string Update_PackageArch_X86 => ResourceManager.GetString(nameof(Update_PackageArch_X86), _resourceCulture);

        public static string Update_Preview => ResourceManager.GetString(nameof(Update_Preview), _resourceCulture);

        public static string Update_Release => ResourceManager.GetString(nameof(Update_Release), _resourceCulture);
    }
}